# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'practice_closure' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for practice_closure

  target 'practice_closureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'practice_closureUITests' do
    # Pods for testing
  end

end
